<?php
$collection = $this->getCollection();
echo $this->getPagerHtml();
if ($collection->getData() !== null) : $collection->getSize();
?>
        <table id="pagination-table">
            <?php foreach($collection as $value) :?>
                <tr>
                    <td><h1><?php echo $value->getName() ?></h1></td>
                </tr>
            <?php endforeach ?>
        </table>
   
<?php endif;
